language: swift
osx_image: xcode11.3
script: xcodebuild clean build test -project Airports.xcodeproj/ -scheme Airports -sdk iphonesimulator -configuration Debug -enableCodeCoverage YES -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO VALID_ARCHS=x86_64
after_success: bash <(curl -s https://codecov.io/bash)
